const TokenType = {
	ALTERNATE: 'alternate',
	ANY: 'any',
	BACK_REFERENCE: 'back-reference',
	BACKSPACE: 'backspace',
	BEGIN: 'begin',
	CAPTURE_GROUP: 'capture-group',
	CARRIAGE_RETURN: 'carriage-return',
	CHARSET: 'charset',
	CONTROL: 'control',
	DIGIT: 'digit',
	END: 'end',
	ESCAPE: 'escape',
	FORM_FEED: 'form-feed',
	HEX: 'hex',
	LINE_FEED: 'line-feed',
	LITERAL: 'literal',
	MATCH: 'match',
	MODIFIED_GROUP: 'modified-group',
	MODIFIER: 'modifier',
	NAMED_BACK_REFERENCE: 'named-back-reference',
	NAMED_GROUP: 'named-group',
	NEGATIVE_LOOKAHEAD: 'negative-lookahead',
	NEGATIVE_LOOKBEHIND: 'negative-lookbehind',
	NON_CAPTURE_GROUP: 'non-capture-group',
	NON_DIGIT: 'non-digit',
	NON_UNICODE_PROPERTY: 'non-unicode-property',
	NON_WHITE_SPACE: 'non-white-space',
	NON_WORD: 'non-word',
	NON_WORD_BOUNDARY: 'non-word-boundary',
	NUL: 'nul',
	OCTAL: 'octal',
	PATTERN: 'pattern',
	POSITIVE_LOOKAHEAD: 'positive-lookahead',
	POSITIVE_LOOKBEHIND: 'positive-lookbehind',
	QUANTIFIED: 'quantified',
	QUANTIFIER: 'quantifier',
	RANGE: 'range',
	TAB: 'tab',
	UNICODE: 'unicode',
	UNICODE_PROPERTY: 'unicode-property',
	UTF16: 'utf-16',
	VERTICAL_TAB: 'vertical-tab',
	WHITE_SPACE: 'white-space',
	WORD: 'word',
	WORD_BOUNDARY: 'word-boundary'
}

module.exports = {
	TokenType
}
